services:
  - type: web
    name: vampiretech-md
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node --no-warnings --experimental-global-webcrypto index.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_NAME
        value: Vampire MD
      - key: PREFIX
        value: .
      - key: SESSION_ID
        value: 
        sync: false
      - key: AUTO_VIEW_STATUS
        value: true
      - key: AUTO_REACT
        value: false
      - key: PRESENCE
        value: true
      - key: RATE_LIMIT
        value: true
      - key: BOT_MODE
        value: public
